import type { Metadata } from "next";
import { Mulish } from 'next/font/google'

import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
const inter = Mulish({
  
  display: 'swap',
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className} suppressHydrationWarning>
      <body suppressHydrationWarning>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
